#!/bin/bash
cat <<EOF > 0-object_like_macro.h
#ifndef OBJECT_LIKE_MACRO_H
#define OBJECT_LIKE_MACRO_H

#define SIZE 1024

#endif /*OBJECT_LIKE_MACRO_H*/

EOF

cat <<EOF > 1-pi.h
#ifndef PI_H
#define PI_H

#define PI 3.14159265359

#endif /*PI_H*/
EOF

cat <<EOF > 2-main.c
#include <stdio.h>

/**
 * main - Function to print file name with newline
 * Return: 0
 */
int main(void)
{
	printf("%s\n", __FILE__);
	return (0);
}
EOF

cat <<EOF > 3-function_like_macro.h
#ifndef FUNCTION_LIKE_MACRO_H
#define FUNCTION_LIKE_MACRO_H

#define ABS(x) ((x) < 0 ? -(x) : (x))

#endif
EOF

cat <<EOF > 4-sum.h
#ifndef SUM_H
#define SUM_H

#define SUM(x, y) ((x) + (y))

#endif
EOF

cat <<EOF > README.md
0x0D-preprocessor
EOF


