#!/bin/bash
cat <<EOF > 1-args.c
#include <stdio.h>

/**
 * main - Number of arguments passed into it
 * @argc: arguments counts
 * @argv: arguments arrays
 * Return: Always 0 success
 */
int main(int argc, char **argv)
{
	(void)argv;

	printf("%d\n", argc - 1);
	return (0);
}
EOF

#!/bin/bash
cat <<EOF > 2-args.c
#include <stdio.h>

/**
 * main - Program that prints all arguments it receives.
 * @argc: arguments count
 * @argv: Arrays of arguments
 * Return: Alway 0 Success
 */
int main(int argc, char **argv)
{
	int i;

	for (i = 0; i < argc; i++)
	{
		printf("%s\n", argv[i]);
	}
	return (0);
}
EOF

#!/bin/bash
cat <<EOF > 3-mul.c
#include <stdio.h>
#include <stdlib.h>

/**
 * main - Program that multiplies two numbers
 * @argc: argumet counts
 * @argv: Array of arguments
 * Return: 0 for success 1 otherwise
 */
int main(int argc, char **argv)
{
	int i, x;

	if (argc < 3)
	{
		printf("Error\n");
		return (1);
	}

	i = atoi(argv[1]);
	x = atoi(argv[2]);
	printf("%d\n", i * x);
	return (0);
}
EOF

#!/bin/bash
cat <<EOF > 4-add.c
#include <stdio.h>
#include <stdlib.h>

/**
 * main - Program that adds positive numbers
 * @argc: argument counts
 * @argv: Array of arguments
 * Return: Always 0 Success
 */
int main(int argc, char **argv)
{
	int x, i, sum = 0;
	char *flag;

	if (argc < 2)
	{
		printf("0\n");
		return (0);
	}

	for (x = 1; argv[x]; x++)
	{
		i = strtol(argv[x], &flag, 10);
		if (*flag)
		{
			printf("Error\n");
			return (1);
		}
		else
		{
			sum += i;
		}
	}
	printf("%d\n", sum);

	return (0);
}
EOF

#!/bin/bash
cat <<EOF > 100-change.c
#include <stdio.h>
#include <stdlib.h>

/**
 * main - Program that prints the min number of
 * coins to make change for an amount of money.
 * @argc: argument count
 * @argv: Array arguments
 * Return: 0 Success, 1 Error
 */
int main(int argc, char **argv)
{
	int total, count;
	unsigned int i;
	char *p;
	int cents[] = {25, 10, 5, 2};

	if (argc != 2)
	{
		printf("Error\n");
		return (1);
	}

	total = strtol(argv[1], &p, 10);
	count = 0;

	if (!*p)
	{
		while (total > 1)
		{
			for (i = 0; i < sizeof(cents[i]); i++)
			{
				if (total >= cents[i])
				{
					count += total / cents[i];
					total = total % cents[i];
				}
			}
		}
		if (total == 1)
			count++;
	}
	else
	{
		printf("Error\n");
		return (1);
	}

	printf("%d\n", count);
	return (0);
}
EOF

